name: Desligamentos

on:
  schedule:
    - cron: '0 11 * * *'  # 08:00 Brasil
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4   # ✅ atualizado

      - name: Instalar Python
        uses: actions/setup-python@v5   # ✅ atualizado
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar script
        run: python Desliga.py

      - name: Upload do arquivo
        uses: actions/upload-artifact@v4
        with:
          name: desligamentos
          path: Desligados_*.json  
